### ISSUE TITLE
VideoCaptureElement pop ActiveMovie Window in my computer

### ISSUE THREAD

**Issue by wormday** [Sascha-L/WPF-MediaKit#38]
but is right on other computers

**Comment by xmedeko** [comment]
I do not understand what the problem. Note: this project is a player only, you should check your codecs first if you have problem just on some machines.

**Comment by co2chicken** [comment]
Hello--

I suspect wormday might be trying address the same issue I'm having.

I use WPFMediaKit to display and capture webcam images. Just like the basic example on your wiki. 

Within the last week, for some unknown reason, when the VideoCaptureElement is started, the webcam video shows up in a separate ActiveMovie window and the VideoCaptureElement is blank. Last week, it worked just fine. This only happens when I select the Logitech USB camera as the VideoCaptureDevice. When I select the built-in webcam on the laptop, the video still shows normally within the VideoCaptureElement.

I have read elsewhere that this may be due to ActiveMovie becoming the default player, somehow, for the logitech camera. I'm going to try uninstalling Windows Media Player and then reinstalling the Logitech Webcam Drivers. But this has become a headache.

Ben

**Comment by xmedeko** [comment]
Looks like a problem after some Windows or driver update. @co2chicken did the reinstalling help?

**Comment by wormday** [comment]
After I upgrade to the new version, this issue no longer reproduce.
thank you~
