### ISSUE TITLE
[Suggestion] Enable usage of Microsoft Media Foundation to not necessitate installation of codec packs

### ISSUE THREAD

**Issue by gthvidsten** [Sascha-L/WPF-MediaKit#43]
A standard video/mp4 video from Twitter will not play without installing additional codecs, like [K-Lite](https://www.codecguide.com/download_kl.htm). Here's one [example](https://video.twimg.com/tweet_video/DCLI6K5UIAEmH9R.mp4).

This file plays just fine in browsers and Windows Media Player, which should mean that Windows has the appropriate codecs. However, it would not play in WPF-MediaKit until I installed K-Lite.

WPF-MediaKit should use default Windows codecs.

**Comment by fabcal24** [comment]
WPF MediaKit is a layer for allowing Directx/Directshow functions in WPF. Windows Media Player use Microsoft Media Foundation codec provided into Windows (Vista or above). Your suggestion isn't a bug and is normally to install 3rd party Direct Show Codecs. I suggest you use Lavfilters (ffmpeg based) instead of K-Lite Codecs. Lavfilters also support all formats, included mkv,

**Comment by gthvidsten** [comment]
Are there any plans to integrate with Microsoft Media Foundation? It would be nice to distribute a single package that allows video playback without also having to tell the end-user to install codec packs.

**Comment by fabcal24** [comment]
You can change this issue in suggestion.

**Comment by skaterlui** [comment]
If you like to use media foundation you can use the mediaelement control provided within wpf. This control doesn't provide features like framestep or fastforward without dropping frames. If you need just a simple player control try mediaelement.

**Comment by fabcal24** [comment]
Skaterlui, i think wpf mediakit is fantastic. I see source code and at this time i'm busy with my work, but in future i thnik to contribute. In my other project I implements some functions, like framestep and fastforward without loosing frames with directshow, but not in wpf. I think try implements this in wpf mediakit. I'm happy for this project. Actually I made some changes, like stop and go to 0 time automatically, improvement of cpu  load (work in progress...) and Others. ;-). I think to complete this fast and I'll share soon my implementations. Scuse for bad english

**Comment by skaterlui** [comment]
Hey fabcal, I think the same. I'm using it since 5 years about. Have a look at [my app](https://www.youtube.com/watch?v=QVx-_HpHe7c) with mediakit. Check my patches at the fork. There you can find my changes for framestep.

**Comment by fabcal24** [comment]
Thank you very much :-)

**Comment by gthvidsten** [comment]
@skaterlui Unfortunately, I can't use the MediaElement control in WPF because I need to play videos from https sources, which that control doesn't support :(

**Comment by fabcal24** [comment]
gthvidsten you need 3rd party codec in directshow, if you want use wpf mediakit. This is only right way. If you use lavfilters, this support also hls (httplivestreaming) and rtsp/rtmp streaming

**Comment by xmedeko** [comment]
@gthvidsten It would be nice to be able to use MMF, but I am afraid it's not possible. So, I am closing this feature requests.

I just may recommend to use https://ninite.com/ to install K-Lite, since it's without the PUA - potentially unwanted applications.

**Comment by glenn-slayden** [comment]
I just recently developed a separate C#-only project which terminates a **Media Foundation** video pipeline--running in **Direct3D 11** (DXGI) mode--as a **WPF** `FrameworkElement` with no so-called "airspace" issues. This is implemented as a `D3DImage` approach that implements the `IMFMediaSink` (and `IMFMediaStream`) interfaces. This code will be published on GitHub as soon as I can. Contact me if you need more information sooner.

**Comment by xmedeko** [comment]
@glenn-slayden Since you know WPF-MediaKit and DirectShow, do you think it would be possible to have just one versatile video player project, which could use (switch):
- codecs framework: DirectShow or Media Foundation
- render: D3DImage, Direct3D 11, EVR
My rough idea would be NuGet packages something like: `WPFplayer-core` (just abstract classes), `WPFplayer-DirectShow`, `WPFplayer-MMF`, `WPFplayer-D3DImage11`, ... etc. so a user would install what she needs.

**Comment by glenn-slayden** [comment]
> @glenn-slayden Since you know WPF-MediaKit and DirectShow...

@xmedeko  By saying "...implements the `IMFMediaSink` (and `IMFMediaStream`) interfaces..." I meant to imply that most of my development work focuses on the wholesale abandonment ***DirectShow*** in favor of the more recent--albeit somewhat obtuse--***Windows Media Framework***.

**Comment by xmedeko** [comment]
After a few years more experience with DirectShow, WPF-MediaKit, codecs installation, licences etc. I think the abandoned  _**DirectShow**_ should be really just for the people who are sure that they need some features which _**Windows Media Framework**_ does not have. So, I have changed my mind, @glenn-slayden just go ahead with separate implementation and do not are about any WPF-MediaKit compatibility.

**Comment by glenn-slayden** [comment]
@xmedeko  I'm not saying WMF is better. In fact, it's clearly worse (in terms of device support and adoption). But for me, WMF is a fine way to go because it does in fact support my devices, and I guess I kinda like it because, as nobody can deny, it's much more retro-futuristic, insofar as it pushes **COM** to its ultimate ridiculous conclusion and limits.
